name: Build and Package WordPress Plugin

# Permissions nécessaires pour créer la release
permissions:
  contents: write
  packages: write

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl
          tools: composer

      - name: Install dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      - name: Create distribution ZIP
        run: |
          echo "📦 Création du ZIP du plugin..."
          # On exclut uniquement les fichiers listés dans .distignore sauf le vendor/
          EXCLUDES=$(grep -v '^vendor/' .distignore | tr '\n' ' ')
          zip -r newsletter-optin-block.zip * -x $EXCLUDES

      - name: Verify ZIP contents
        run: |
          echo "✅ Contenu du ZIP :"
          unzip -l newsletter-optin-block.zip

      - name: Upload ZIP as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: newsletter-optin-block
          path: newsletter-optin-block.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: newsletter-optin-block.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
